pub mod catalog;
pub mod cli;
pub(crate) mod client_config;
pub(crate) mod client_runtime;
pub mod context;
pub mod doctor;
pub mod mcp;
pub(crate) mod opencode_config;
pub use opencode_config::Format as OpenCodeFormat;
pub mod policy;
pub mod selection;
pub mod service;
pub mod setup;
pub mod types;
