use crossterm::event::KeyEvent;
use uuid::Uuid;

use crate::db::{
    ErrorCategory, ServerInfo,
    catalog::{
        CatalogCapabilities, CatalogDiscovery, CatalogPage, CatalogRequest, CatalogRequestKey,
        CatalogTarget,
    },
    query::QueryOutcome,
};
use crate::{
    model::{
        explorer::ExplorerNodeId,
        profile_manager::{
            DiscoveryFingerprint, ProfileChange, ProfileField, ProfileInput, ProfileSubmission,
        },
        workspace::{ConnectionIdentity, Focus},
    },
    profile::ConnectionProfile,
};

#[derive(Clone, Debug, PartialEq)]
pub enum Action {
    NewConsole,
    CloseActiveTab,
    NextTab,
    PreviousTab,
    ActivateTab(usize),
    FocusNext,
    FocusPrevious,
    Focus(Focus),
    ShowHelp,
    DismissOverlay,
    SubstituteYes,
    SubstituteNo,
    SubstituteAll,
    SubstituteLast,
    SubstituteQuit,
    OpenProfileManager,
    CloseProfileManager,
    ProfileStartNew,
    ProfileStartEdit {
        profile_id: Uuid,
    },
    ProfileRequestDelete {
        profile_id: Uuid,
    },
    ProfileConfirmDelete,
    ProfileCancelDelete,
    ProfileFieldNext,
    ProfileFieldPrevious,
    ProfileFocusField(ProfileField),
    ProfileInsert(ProfileInput),
    ProfilePaste(ProfileInput),
    ProfileBackspace,
    ProfileDeleteCharacter,
    ProfileMoveLeft,
    ProfileMoveRight,
    ProfileMoveHome,
    ProfileMoveEnd,
    ProfileCycle(i8),
    ProfileToggle,
    ProfileToggleField(ProfileField),
    ProfileOpenScope,
    ProfileToggleScopeRow(String),
    ProfileScopeMove(isize),
    ProfileScopeBack,
    ProfileTest,
    ProfileSave {
        connect: bool,
    },
    ProfileTestSucceeded {
        request_id: u64,
        fingerprint: DiscoveryFingerprint,
        server: ServerInfo,
        capabilities: CatalogCapabilities,
        discovery: Result<CatalogDiscovery, String>,
    },
    ProfileTestFailed {
        request_id: u64,
        message: String,
    },
    ProfileSaved {
        request_id: u64,
        profile: ConnectionProfile,
        warning: Option<String>,
        change: ProfileChange,
        connect: bool,
    },
    ProfileSaveFailed {
        request_id: u64,
        message: String,
    },
    ProfileDeleted {
        request_id: u64,
        profile_id: Uuid,
        active_connection: Option<ConnectionIdentity>,
    },
    ProfileDeleteFailed {
        request_id: u64,
        message: String,
    },
    CredentialsRequired {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    DisconnectCompleted {
        connection: ConnectionIdentity,
    },
    ReplaceEditor(String),
    EditorKey(KeyEvent),
    EditorPaste(String),
    EditorViewportChanged(crate::model::editor::EditorViewport),
    EditorScroll {
        rows: isize,
        columns: isize,
    },
    CompletionDue(crate::sql::CompletionScheduleKey),
    CompletionExplicit,
    CompletionNext,
    CompletionPrevious,
    CompletionAccept,
    CompletionDismiss,
    RunActiveSql,
    RunAllSql,
    ConfirmExecution,
    CancelExecution,
    ToggleExecutionConfirmationFocus,
    CancelActiveQuery,
    ConfirmManualCancellation,
    CancelManualCancellation,
    ToggleManualCancellationFocus,
    ConfirmTransactionExit,
    ConfirmTransactionExitChoice(crate::model::transaction::TransactionExitChoice),
    CancelTransactionExit,
    ToggleTransactionExitChoice,
    ConfirmClearTransactionOutcome,
    CancelClearTransactionOutcome,
    OpenTargetSelector,
    MoveTargetSelector(isize),
    ConfirmTargetSelector,
    CancelTargetSelector,
    SetTransactionMode(crate::model::transaction::TransactionMode),
    CommitTransaction,
    RollbackTransaction,
    ClearTransactionOutcome,
    RefreshCatalog,
    ExplorerLoadTarget(CatalogTarget),
    ExplorerOpenSelected,
    OpenSelectedRelation {
        view: crate::model::relation::RelationView,
    },
    SetRelationView(crate::model::relation::RelationView),
    RefreshActiveRelation,
    CancelActiveRelationRequest,
    FocusRelationQueryInput(crate::model::relation::RelationQueryInput),
    RelationQueryInsert(char),
    RelationQueryBackspace,
    RelationQueryDelete,
    RelationQueryMoveLeft,
    RelationQueryMoveRight,
    RelationQueryMoveHome,
    RelationQueryMoveEnd,
    RelationQueryClear,
    SubmitRelationQuery,
    CancelRelationQueryInput,
    ResizeRelationColumn(i16),
    ResetRelationColumnWidth,
    StartRelationColumnResize {
        column: usize,
        width: u16,
    },
    SetRelationColumnWidth {
        column: usize,
        width: u16,
    },
    EndRelationColumnResize,
    PreviewSelected,
    DdlSelected,
    RelationSucceeded {
        request: crate::model::relation::RelationRequest,
        snapshot: Box<crate::model::relation::RelationSnapshot>,
    },
    RelationFailed {
        request: crate::model::relation::RelationRequest,
        message: String,
    },
    RequestProfileConnect {
        profile_id: Uuid,
    },
    RequestConnect(Uuid),
    RequestProfileDisconnect {
        profile_id: Uuid,
    },
    ConnectionSucceeded {
        profile_id: Uuid,
        generation: u64,
        server: ServerInfo,
    },
    ConnectionFailed {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    ConnectionInvalidated {
        connection: ConnectionIdentity,
        message: String,
    },
    CatalogPageLoaded(CatalogPage),
    CatalogPageFailed {
        key: CatalogRequestKey,
        category: ErrorCategory,
        message: String,
    },
    QueryFinished {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    QueryFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualStarted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualStartFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualQueryFinished {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    ManualQueryFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualImplicitlyEnded {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    ManualRolledBack {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualRollbackFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    ExplorerMove(isize),
    ExplorerSelect(ExplorerNodeId),
    ExplorerToggle,
    ExplorerExpand,
    ExplorerCollapse,
    ExplorerPrimary,
    ExplorerRefresh,
    GridMove {
        rows: isize,
        columns: isize,
    },
    GridSelect {
        row: usize,
        column: usize,
    },
    ToggleResultView,
    Quit,
}

#[derive(Clone, Debug)]
pub enum Command {
    TestProfile {
        request_id: u64,
        submission: ProfileSubmission,
    },
    SaveProfile {
        request_id: u64,
        submission: ProfileSubmission,
        connect: bool,
    },
    DeleteProfile {
        request_id: u64,
        profile_id: Uuid,
    },
    Disconnect {
        connection: ConnectionIdentity,
    },
    Connect {
        profile_id: Uuid,
        generation: u64,
    },
    LoadCatalogPage(CatalogRequest),
    LoadRelationPreview(crate::model::relation::RelationRequest),
    LoadRelationStructure(crate::model::relation::RelationRequest),
    CancelRelationRequest(crate::model::relation::RelationRequest),
    RunQuery {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        generation: u64,
        sql: String,
    },
    ManualBegin {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualExecute {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        sql: String,
    },
    ManualCommit {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualRollback {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    CancelQuery {
        tab_id: Uuid,
        generation: u64,
    },
    CancelManual {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    PersistWorkspace,
    ScheduleCompletion(crate::sql::CompletionScheduleKey),
    Quit,
}
