use crossterm::event::KeyEvent;
use uuid::Uuid;

use crate::db::{
    ServerInfo,
    catalog::{CatalogKind, CatalogNode},
    query::QueryOutcome,
};
use crate::{
    model::{
        profile_manager::{ProfileField, ProfileInput, ProfileSubmission},
        workspace::{ConnectionIdentity, Focus},
    },
    profile::ConnectionProfile,
};

#[derive(Clone, Debug, PartialEq)]
pub enum Action {
    NewConsole,
    CloseActiveTab,
    NextTab,
    PreviousTab,
    ActivateTab(usize),
    FocusNext,
    FocusPrevious,
    Focus(Focus),
    ShowHelp,
    DismissOverlay,
    SubstituteYes,
    SubstituteNo,
    SubstituteAll,
    SubstituteLast,
    SubstituteQuit,
    OpenProfileManager,
    CloseProfileManager,
    ProfileMove(isize),
    ProfileStartNew,
    ProfileStartEdit,
    ProfileRequestDelete,
    ProfileConfirmDelete,
    ProfileCancelDelete,
    ProfileConnectSelected,
    ProfileFieldNext,
    ProfileFieldPrevious,
    ProfileFocusField(ProfileField),
    ProfileInsert(ProfileInput),
    ProfilePaste(ProfileInput),
    ProfileBackspace,
    ProfileDeleteCharacter,
    ProfileMoveLeft,
    ProfileMoveRight,
    ProfileMoveHome,
    ProfileMoveEnd,
    ProfileCycle(i8),
    ProfileToggle,
    ProfileToggleField(ProfileField),
    ProfileTest,
    ProfileSave {
        connect: bool,
    },
    ProfileTestSucceeded {
        request_id: u64,
        server: ServerInfo,
    },
    ProfileTestFailed {
        request_id: u64,
        message: String,
    },
    ProfileSaved {
        request_id: u64,
        profile: ConnectionProfile,
        warning: Option<String>,
        connect: bool,
    },
    ProfileSaveFailed {
        request_id: u64,
        message: String,
    },
    ProfileDeleted {
        request_id: u64,
        profile_id: Uuid,
        active_connection: Option<ConnectionIdentity>,
    },
    ProfileDeleteFailed {
        request_id: u64,
        message: String,
    },
    CredentialsRequired {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    DisconnectCompleted {
        connection: ConnectionIdentity,
    },
    ReplaceEditor(String),
    EditorKey(KeyEvent),
    EditorPaste(String),
    EditorViewportChanged(crate::model::editor::EditorViewport),
    EditorScroll {
        rows: isize,
        columns: isize,
    },
    CompletionDue(crate::sql::CompletionScheduleKey),
    CompletionExplicit,
    CompletionNext,
    CompletionPrevious,
    CompletionAccept,
    CompletionDismiss,
    RunActiveSql,
    RunAllSql,
    ConfirmExecution,
    CancelExecution,
    ToggleExecutionConfirmationFocus,
    CancelActiveQuery,
    ConfirmManualCancellation,
    CancelManualCancellation,
    ToggleManualCancellationFocus,
    ConfirmTransactionExit,
    ConfirmTransactionExitChoice(crate::model::transaction::TransactionExitChoice),
    CancelTransactionExit,
    ToggleTransactionExitChoice,
    ConfirmClearTransactionOutcome,
    CancelClearTransactionOutcome,
    SetTransactionMode(crate::model::transaction::TransactionMode),
    CommitTransaction,
    RollbackTransaction,
    ClearTransactionOutcome,
    RefreshCatalog,
    PreviewSelected,
    DdlSelected,
    RequestConnect(Uuid),
    ConnectionSucceeded {
        profile_id: Uuid,
        generation: u64,
        server: ServerInfo,
    },
    ConnectionFailed {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    CatalogLoaded {
        profile_id: Uuid,
        generation: u64,
        nodes: Vec<CatalogNode>,
    },
    CatalogFailed {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    QueryFinished {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    QueryFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualStarted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualStartFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualQueryFinished {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    ManualQueryFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualImplicitlyEnded {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    ManualRolledBack {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualRollbackFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    PreviewFinished {
        tab_id: Uuid,
        generation: u64,
        sql: String,
        outcome: QueryOutcome,
    },
    DdlLoaded {
        tab_id: Uuid,
        generation: u64,
        ddl: String,
    },
    ExplorerMove(isize),
    ExplorerSelect(usize),
    ExplorerToggle,
    GridMove {
        rows: isize,
        columns: isize,
    },
    GridSelect {
        row: usize,
        column: usize,
    },
    ToggleResultView,
    Quit,
}

#[derive(Clone, Debug)]
pub enum Command {
    TestProfile {
        request_id: u64,
        submission: ProfileSubmission,
    },
    SaveProfile {
        request_id: u64,
        submission: ProfileSubmission,
        connect: bool,
    },
    DeleteProfile {
        request_id: u64,
        profile_id: Uuid,
    },
    Disconnect {
        connection: ConnectionIdentity,
    },
    Connect {
        profile_id: Uuid,
        generation: u64,
    },
    LoadCatalog {
        profile_id: Uuid,
        generation: u64,
    },
    RunQuery {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        generation: u64,
        sql: String,
    },
    ManualBegin {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualExecute {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        sql: String,
    },
    ManualCommit {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualRollback {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    PreviewTable {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        generation: u64,
        schema: String,
        name: String,
    },
    LoadDdl {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        generation: u64,
        kind: CatalogKind,
        schema: String,
        name: String,
    },
    CancelQuery {
        tab_id: Uuid,
        generation: u64,
    },
    CancelManual {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    PersistWorkspace(crate::persistence::workspace::WorkspaceSnapshot),
    ScheduleCompletion(crate::sql::CompletionScheduleKey),
    Quit,
}
