use crossterm::event::KeyEvent;
use std::path::PathBuf;
use uuid::Uuid;

use crate::model::profile_organization::MoveDirection;
use crate::profile::ProfileCollection;

use crate::db::catalog_mutation::{
    CatalogMutationCapabilities, CatalogMutationPlan, CatalogMutationRequest,
    CatalogObjectDefinition, CatalogObjectDefinitionRequest, CatalogOwnerContext,
    CatalogOwnerContextRequest,
};
use crate::db::{
    ErrorCategory, ServerInfo,
    catalog::{
        CatalogCapabilities, CatalogDiscovery, CatalogPage, CatalogRequest, CatalogRequestKey,
        CatalogSearchPage, CatalogSearchRequest, CatalogTarget,
    },
    catalog_drop::{CatalogDropError, CatalogDropPlan, CatalogDropRequest},
    query::QueryOutcome,
};
use crate::{
    clipboard::ClipboardPayload,
    help::HelpShortcutId,
    model::{
        execution_target::ExecutionTarget,
        explorer::ExplorerNodeId,
        profile_manager::{
            DiscoveryFingerprint, ProfileChange, ProfileField, ProfileInput, ProfileSubmission,
        },
        workspace::{ConnectionIdentity, Focus, PaneLayoutMetrics, PaneResize},
    },
    persistence::secrets::SecretStoreAvailability,
    profile::{ConnectionProfile, DatabaseKind},
};

#[derive(Clone, Debug, PartialEq)]
pub enum Action {
    NewConsole,
    OpenDashboard,
    DashboardSetPage(crate::model::dashboard::DashboardPage),
    DashboardRefresh,
    DashboardTogglePolling,
    DashboardProcessFilterInsert(char),
    DashboardProcessFilterBackspace,
    DashboardProcessFilterClear,
    DashboardProcessFilterStart,
    DashboardProcessFilterCommit,
    DashboardProcessFilterCancel,
    DashboardProcessFilterDeletePreviousWord,
    DashboardProcessFilterDeleteToStart,
    DashboardProcessFilterDelete,
    DashboardProcessFilterMoveLeft,
    DashboardProcessFilterMoveRight,
    DashboardProcessFilterMoveHome,
    DashboardProcessFilterMoveEnd,
    DashboardMetricsDue,
    DashboardProcessesDue,
    CloseActiveTab,
    CloseOtherTabs,
    CloseTab(Uuid),
    RequestDeleteActiveConsole,
    ConfirmDeleteConsole,
    CancelDeleteConsole,
    OpenSqlEditorList,
    SqlEditorListMove(isize),
    SqlEditorListActivate,
    SqlEditorListCreate,
    SqlEditorListDeleteRequest,
    SqlEditorListDeleteConfirm,
    SqlEditorListDeleteCancel,
    SqlEditorListSearchStart,
    SqlEditorListRenameStart,
    SqlEditorListRenameCommit,
    SqlEditorListInputInsert(char),
    SqlEditorListInputBackspace,
    SqlEditorListInputDeletePreviousWord,
    SqlEditorListInputDeleteToStart,
    SqlEditorListInputDelete,
    SqlEditorListInputMoveLeft,
    SqlEditorListInputMoveRight,
    SqlEditorListInputMoveHome,
    SqlEditorListInputMoveEnd,
    SqlEditorListCancel,
    ActivateSqlEditor(Uuid),
    NextTab,
    PreviousTab,
    ActivateTab(usize),
    FocusNext,
    FocusPrevious,
    Focus(Focus),
    TogglePaneMaximized,
    ResizePane(PaneResize),
    ResetPaneSizes,
    PaneLayoutChanged(PaneLayoutMetrics),
    ShowHelp,
    DismissOverlay,
    DismissNotification(u64),
    OpenNotificationHistory,
    NotificationHistorySearchOpen,
    NotificationHistorySearchInsert(char),
    NotificationHistorySearchBackspace,
    NotificationHistorySearchClear,
    NotificationHistorySearchConfirm,
    NotificationHistoryNext,
    NotificationHistoryPrevious,
    NotificationHistoryMove(isize),
    NotificationHistoryClear,
    NotificationHistoryClearConfirm,
    NotificationHistoryClearCancel,
    HelpEdit(crate::model::text_input::TextInputEdit),
    HelpPaste(String),
    HelpMove(isize),
    ExecuteHelpShortcut(HelpShortcutId),
    SubstituteYes,
    SubstituteNo,
    SubstituteAll,
    SubstituteLast,
    SubstituteQuit,
    OpenProfileManager,
    SystemCredentialAvailability(SecretStoreAvailability),
    CloseProfileManager,
    ProfileStartNew,
    ProfileStartEdit {
        profile_id: Uuid,
    },
    OpenExplorerAdd,
    ExplorerAddMove(isize),
    ExplorerAddSelect(usize),
    ExplorerAddConfirm,
    ExplorerAddCancel,
    OpenCatalogCreate,
    OpenCatalogEdit,
    ProfileRequestDelete {
        profile_id: Uuid,
    },
    RequestDropCatalogObject {
        id: crate::db::catalog::CatalogId,
    },
    CatalogDropPlanReady(CatalogDropPlan),
    CatalogDropPlanFailed {
        request: CatalogDropRequest,
        error: CatalogDropError,
    },
    CatalogDropSucceeded {
        plan: CatalogDropPlan,
        outcome: QueryOutcome,
    },
    CatalogDropFailed {
        plan: CatalogDropPlan,
        message: String,
    },
    CatalogMutationPlanReady(CatalogMutationPlan),
    CatalogMutationPlanFailed {
        request: CatalogMutationRequest,
        message: String,
    },
    CatalogMutationSucceeded {
        plan: CatalogMutationPlan,
        outcome: QueryOutcome,
    },
    CatalogMutationFailed {
        plan: CatalogMutationPlan,
        message: String,
    },
    CatalogObjectDefinitionLoaded {
        request: CatalogObjectDefinitionRequest,
        definition: CatalogObjectDefinition,
    },
    CatalogObjectDefinitionLoadFailed {
        request: CatalogObjectDefinitionRequest,
        message: String,
    },
    CatalogOwnerContextLoaded {
        request: CatalogOwnerContextRequest,
        context: CatalogOwnerContext,
    },
    CatalogOwnerContextLoadFailed {
        request: CatalogOwnerContextRequest,
        message: String,
    },
    CatalogDropInsert(char),
    CatalogDropBackspace,
    CatalogDropClear,
    CatalogDropConfirm,
    CatalogDropCancel,
    CatalogEditorCancel,
    CatalogEditorMove(isize),
    CatalogEditorSelect,
    CatalogEditorFieldNext,
    CatalogEditorFieldPrevious,
    CatalogEditorFocusField(usize),
    CatalogOwnerPickerOpen,
    CatalogOwnerPickerClose,
    CatalogOwnerPickerMove(isize),
    CatalogOwnerPickerInsert(char),
    CatalogOwnerPickerBackspace,
    CatalogOwnerPickerDeletePreviousWord,
    CatalogOwnerPickerDeleteToStart,
    CatalogOwnerPickerAccept,
    CatalogOwnerPickerChoose(String),
    CatalogEditorInsert(char),
    CatalogEditorPaste(String),
    CatalogEditorBackspace,
    CatalogEditorDeletePreviousWord,
    CatalogEditorDeleteToStart,
    CatalogEditorDelete,
    CatalogEditorMoveLeft,
    CatalogEditorMoveRight,
    CatalogEditorMoveHome,
    CatalogEditorMoveEnd,
    CatalogEditorToggleMaterializedViewData,
    CatalogEditorPreview,
    CatalogEditorApply,
    CatalogEditorBack,
    CatalogEditorConfirmInsert(char),
    CatalogEditorFocusTableField(crate::model::catalog_editor::TableEditorFocus),
    CatalogEditorSelectTableColumn(usize),
    CatalogEditorOpenTableColumnDetails,
    CatalogEditorConfirmTableColumnDetails,
    CatalogEditorCancelTableColumnDetails,
    CatalogEditorMoveTableColumn(isize),
    CatalogEditorAddTableColumn,
    CatalogEditorRemoveTableColumn,
    CatalogEditorToggleTableColumnNullable,
    CatalogEditorToggleTableColumnIdentity,
    ProfileConfirmDelete,
    ProfileCancelDelete,
    ProfileFieldNext,
    ProfileFieldPrevious,
    ProfileFocusField(ProfileField),
    ProfileInsert(ProfileInput),
    ProfilePaste(ProfileInput),
    ProfileBackspace,
    ProfileDeletePreviousWord,
    ProfileDeleteToStart,
    ProfileDeleteCharacter,
    ProfileMoveLeft,
    ProfileMoveRight,
    ProfileMoveHome,
    ProfileMoveEnd,
    ProfileCommitUrl,
    ProfileCycle(i8),
    ProfileSelectDriver(DatabaseKind),
    ProfileToggle,
    ProfileToggleField(ProfileField),
    ProfileOpenScope,
    ProfileRefreshScope,
    ProfileToggleScopeRow(String),
    ProfileScopeMove(isize),
    ProfileScopeBack,
    ProfileTest,
    ProfileSave {
        connect: bool,
    },
    ProfileTestSucceeded {
        request_id: u64,
        fingerprint: DiscoveryFingerprint,
        server: ServerInfo,
        capabilities: CatalogCapabilities,
        discovery: Result<CatalogDiscovery, String>,
    },
    ProfileTestFailed {
        request_id: u64,
        message: String,
    },
    ProfileCatalogDiscoverySucceeded {
        request_id: u64,
        fingerprint: DiscoveryFingerprint,
        server: ServerInfo,
        capabilities: CatalogCapabilities,
        discovery: CatalogDiscovery,
    },
    ProfileCatalogDiscoveryFailed {
        request_id: u64,
        fingerprint: DiscoveryFingerprint,
        message: String,
    },
    ProfileSaved {
        request_id: u64,
        profile: ConnectionProfile,
        warning: Option<String>,
        change: ProfileChange,
        connect: bool,
    },
    ProfileSaveFailed {
        request_id: u64,
        message: String,
    },
    OpenProfileAccess,
    ProfileAccessMove(isize),
    ProfileAccessConfirm,
    ProfileAccessCancel,
    ProfileGroupOpen,
    ProfileGroupCreate,
    ProfileGroupMove(isize),
    ProfileGroupSelect(usize),
    ProfileGroupEdit(crate::model::text_input::TextInputEdit),
    ProfileGroupConfirm,
    ProfileGroupCancel,
    ProfileGroupDeleteConfirm,
    ProfileAccessUpdated {
        request_id: u64,
        profile_id: Uuid,
        access: crate::profile::ProfileAccess,
    },
    ProfileAccessUpdateFailed {
        request_id: u64,
        profile_id: Uuid,
        message: String,
    },
    ProfileDeleted {
        request_id: u64,
        profile_id: Uuid,
        active_connection: Option<ConnectionIdentity>,
    },
    ProfileDeleteFailed {
        request_id: u64,
        message: String,
    },
    ProfileOrganizationSaved {
        request_id: u64,
        collection: ProfileCollection,
    },
    ProfileOrganizationSaveFailed {
        request_id: u64,
        message: String,
    },
    CredentialsRequired {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    DisconnectCompleted {
        connection: ConnectionIdentity,
    },
    ReplaceEditor(String),
    EditorKey(KeyEvent),
    ReadOnlyEditorKey {
        session_id: Uuid,
        event: KeyEvent,
    },
    ReadOnlyEditorScroll {
        session_id: Uuid,
        rows: isize,
        columns: isize,
    },
    EditorPaste(String),
    CopyEditorYank(String),
    CopyEditorStatement,
    CopyEditorBuffer,
    CopyGridCell,
    CopyGridRow {
        include_headers: bool,
    },
    ClipboardWritten {
        description: String,
    },
    ClipboardWriteFailed {
        message: String,
    },
    EditorViewportChanged(crate::model::editor::EditorViewport),
    EditorScroll {
        rows: isize,
        columns: isize,
    },
    CompletionDue(crate::sql::CompletionScheduleKey),
    CompletionExplicit,
    CompletionNext,
    CompletionPrevious,
    CompletionAccept,
    CompletionDismiss,
    RunActiveSql,
    RunAllSql,
    ConfirmExecution,
    CancelExecution,
    ToggleExecutionConfirmationFocus,
    CancelActiveQuery,
    ConfirmManualCancellation,
    CancelManualCancellation,
    ToggleManualCancellationFocus,
    ConfirmTransactionExit,
    ConfirmTransactionExitChoice(crate::model::transaction::TransactionExitChoice),
    CancelTransactionExit,
    ToggleTransactionExitChoice,
    ConfirmClearTransactionOutcome,
    CancelClearTransactionOutcome,
    OpenTargetSelector,
    MoveTargetSelector(isize),
    ConfirmTargetSelector,
    CancelTargetSelector,
    SetTransactionMode(crate::model::transaction::TransactionMode),
    OpenTransactionControl,
    CommitTransaction,
    RollbackTransaction,
    ClearTransactionOutcome,
    RefreshCatalog,
    ExplorerLoadTarget(CatalogTarget),
    ExplorerOpenSelected,
    OpenSelectedRelation {
        view: crate::model::relation::RelationView,
    },
    SetRelationView(crate::model::relation::RelationView),
    SetResultView(crate::model::tab::ResultView),
    RefreshActiveRelation,
    RelationFirstPage,
    RelationPreviousPage,
    RelationNextPage,
    RelationLastPage,
    SetRelationPageSize(crate::model::pagination::PageSize),
    ResultFirstPage,
    ResultPreviousPage,
    ResultNextPage,
    ResultLastPage,
    SetResultPageSize(crate::model::pagination::PageSize),
    OpenPageSizeSelector {
        relation: bool,
    },
    MovePageSizeSelector(isize),
    ConfirmPageSizeSelector,
    CancelPageSizeSelector,
    CancelActiveRelationRequest,
    DdlScroll {
        rows: isize,
        columns: isize,
    },
    DdlScrollToStart,
    DdlScrollToEnd,
    SetDdlViewportMetrics {
        visible_rows: usize,
        visible_columns: usize,
        total_rows: usize,
        max_line_width: usize,
    },
    FocusDataQueryInput(crate::model::data_query::DataQueryInput),
    DataQueryInsert(char),
    DataQueryBackspace,
    DataQueryDeletePreviousWord,
    DataQueryDeleteToStart,
    DataQueryDelete,
    DataQueryMoveLeft,
    DataQueryMoveRight,
    DataQueryMoveHome,
    DataQueryMoveEnd,
    DataQueryClear,
    DataQueryCompletionNext,
    DataQueryCompletionPrevious,
    DataQueryCompletionAccept,
    DataQueryCompletionDismiss,
    SubmitDataQuery,
    CancelDataQueryInput,
    // Kept as reducer aliases for callers using the pre-shared relation names.
    FocusRelationQueryInput(crate::model::relation::RelationQueryInput),
    RelationQueryInsert(char),
    RelationQueryBackspace,
    RelationQueryDelete,
    RelationQueryMoveLeft,
    RelationQueryMoveRight,
    RelationQueryMoveHome,
    RelationQueryMoveEnd,
    RelationQueryClear,
    SubmitRelationQuery,
    CancelRelationQueryInput,
    ResizeRelationColumn(i16),
    ResetRelationColumnWidth,
    StartRelationColumnResize {
        column: usize,
        width: u16,
    },
    SetRelationColumnWidth {
        column: usize,
        width: u16,
    },
    EndRelationColumnResize,
    GridResizeColumn(i16),
    GridResetColumnWidth,
    GridStartColumnResize {
        column: usize,
        width: u16,
    },
    GridSetColumnWidth {
        column: usize,
        width: u16,
    },
    GridEndColumnResize,
    GridSetColumnOffset {
        offset: usize,
    },
    GridScrollColumns {
        offset: usize,
        first_visible: usize,
        last_visible: usize,
    },
    RelationEditCell,
    RelationEditInsert(char),
    RelationEditBackspace,
    RelationEditDeletePreviousWord,
    RelationEditDeleteToStart,
    RelationEditDelete,
    RelationEditMoveLeft,
    RelationEditMoveRight,
    RelationEditMoveHome,
    RelationEditMoveEnd,
    RelationEditConfirm,
    RelationEditCancel,
    RelationVisualLine,
    RelationDeleteCurrent,
    RelationDeleteSelected,
    RelationYank,
    RelationYankSelected,
    RelationPaste,
    RelationInsertRow,
    RelationUndo,
    RelationRedo,
    RelationCommit,
    RelationRollback,
    PreviewSelected,
    DdlSelected,
    RelationSucceeded {
        request: crate::model::relation::RelationRequest,
        snapshot: Box<crate::model::relation::RelationSnapshot>,
    },
    RelationFailed {
        request: crate::model::relation::RelationRequest,
        message: String,
    },
    RelationTransactionStarted {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationTransactionStartFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    RelationMutationSucceeded {
        request: crate::db::mutation::RelationMutationRequest,
        result: crate::db::mutation::MutationResult,
    },
    RelationMutationFailed {
        request: crate::db::mutation::RelationMutationRequest,
        message: String,
    },
    RelationCommitted {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationCommitFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    RelationRolledBack {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationRollbackFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    RequestProfileConnect {
        profile_id: Uuid,
    },
    RequestConnect(Uuid),
    RequestProfileDisconnect {
        profile_id: Uuid,
    },
    ConnectionSucceeded {
        profile_id: Uuid,
        generation: u64,
        server: ServerInfo,
        mutation_capabilities: CatalogMutationCapabilities,
    },
    ConnectionFailed {
        profile_id: Uuid,
        generation: u64,
        message: String,
    },
    ConnectionInvalidated {
        connection: ConnectionIdentity,
        message: String,
    },
    CatalogPageLoaded(CatalogPage),
    CatalogPageFailed {
        key: CatalogRequestKey,
        category: ErrorCategory,
        message: String,
    },
    CatalogSearchSucceeded(CatalogSearchPage),
    CatalogSearchFailed {
        connection: ConnectionIdentity,
        session_id: u64,
        generation: u64,
        message: String,
    },
    QueryFinished {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    DashboardMetricsLoaded {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        snapshot: crate::db::monitor::MonitorSnapshot,
    },
    DashboardMetricsFailed {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    DashboardMetadataLoaded {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        metadata: crate::db::monitor::MonitorMetadata,
    },
    DashboardMetadataFailed {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    DashboardProcessesLoaded {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        snapshot: crate::db::monitor::ProcessSnapshot,
    },
    DashboardProcessesFailed {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    QueryFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    QueryPageFinished {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
        pagination: crate::model::pagination::ResultPagination,
    },
    QueryPageFailed {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    DerivedQueryFinished {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        outcome: QueryOutcome,
    },
    DerivedQueryPageFinished {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        outcome: QueryOutcome,
        pagination: crate::model::pagination::ResultPagination,
    },
    DerivedQueryFailed {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        message: String,
    },
    DerivedQueryPageFailed {
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        message: String,
    },
    ManualStarted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualStartFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualQueryFinished {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
    },
    ManualQueryPageFinished {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        outcome: QueryOutcome,
        pagination: crate::model::pagination::ResultPagination,
    },
    ManualQueryFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualQueryPageFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
    },
    ManualImplicitlyEnded {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitted {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualCommitFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    ManualRolledBack {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
    },
    ManualRollbackFailed {
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        connection: ConnectionIdentity,
        message: String,
        unknown: bool,
    },
    ExplorerMove(isize),
    ExplorerViewportChanged(usize),
    ExplorerSelectTarget(crate::model::explorer::ExplorerNodeTarget),
    ExplorerScrollNodes {
        direction: isize,
        amount: crate::model::explorer::ExplorerScrollAmount,
    },
    ExplorerAlignSelected(crate::model::explorer::ExplorerNodeAlignment),
    ExplorerFindOpen,
    ExplorerFindInsert(char),
    ExplorerFindBackspace,
    ExplorerFindClear,
    ExplorerFindConfirm,
    ExplorerFindNext,
    ExplorerFindPrevious,
    ExplorerFindClose,
    ExplorerSearchOpen,
    ExplorerSearchInsert(char),
    ExplorerSearchBackspace,
    ExplorerSearchClear,
    ExplorerSearchMove(isize),
    ExplorerSearchNext,
    ExplorerSearchPrevious,
    ExplorerSearchLocate,
    ExplorerSearchClose,
    ExplorerSearchRetry,
    ExplorerSelect(ExplorerNodeId),
    CopyExplorerSelection,
    ExplorerToggle,
    ExplorerExpand,
    ExplorerCollapse,
    ExplorerPrimary,
    ExplorerRefresh,
    GridMove {
        rows: isize,
        columns: isize,
    },
    GridSelectRow(crate::model::tab::GridRowTarget),
    GridSelectColumn(crate::model::tab::GridColumnTarget),
    GridScrollRows {
        direction: isize,
        amount: crate::model::tab::GridScrollAmount,
    },
    GridAlignSelectedRow(crate::model::tab::GridRowAlignment),
    GridViewportChanged(crate::model::tab::DataGridViewport),
    OpenRecordView,
    RecordViewMoveFields(isize),
    RecordViewJumpFirstField,
    RecordViewJumpLastField,
    RecordViewMoveRow(isize),
    CloseRecordView,
    RecordViewViewportChanged {
        tab_id: Uuid,
        visible_fields: usize,
    },
    GridSelect {
        row: usize,
        column: usize,
    },
    ToggleResultView,
    Quit,
}

#[allow(clippy::large_enum_variant)]
#[derive(Clone, Debug)]
pub enum Command {
    TestProfile {
        request_id: u64,
        submission: ProfileSubmission,
    },
    DiscoverProfileCatalog {
        request_id: u64,
        submission: ProfileSubmission,
    },
    SaveProfile {
        request_id: u64,
        submission: ProfileSubmission,
        connect: bool,
    },
    DeleteProfile {
        request_id: u64,
        profile_id: Uuid,
    },
    UpdateProfileAccess {
        request_id: u64,
        profile_id: Uuid,
        change: ProfileAccessChange,
    },
    UpdateProfileOrganization {
        request_id: u64,
        mutation: ProfileOrganizationMutation,
    },
    Disconnect {
        connection: ConnectionIdentity,
    },
    Connect {
        profile_id: Uuid,
        generation: u64,
        target: ExecutionTarget,
    },
    LoadCatalogPage(CatalogRequest),
    LoadCatalogObjectDefinition(CatalogObjectDefinitionRequest),
    LoadCatalogOwnerContext(CatalogOwnerContextRequest),
    SearchCatalog(CatalogSearchRequest),
    CancelCatalogSearch,
    PlanCatalogDrop(CatalogDropRequest),
    ExecuteCatalogDrop(CatalogDropPlan),
    PlanCatalogMutation {
        request: CatalogMutationRequest,
        draft: crate::model::catalog_editor::CatalogDraft,
        baseline: Option<CatalogObjectDefinition>,
    },
    ExecuteCatalogMutation(CatalogMutationPlan),
    LoadRelationPreview(crate::model::relation::RelationRequest),
    LoadRelationDdl(crate::model::relation::RelationRequest),
    CancelRelationRequest(crate::model::relation::RelationRequest),
    RunQuery {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        generation: u64,
        sql: String,
    },
    LoadDashboardMetrics {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
    },
    LoadDashboardMetadata {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
    },
    LoadDashboardProcesses {
        tab_id: Uuid,
        tab_generation: u64,
        connection: ConnectionIdentity,
    },
    CancelDashboardTasks {
        tab_id: Uuid,
        tab_generation: u64,
    },
    RunQueryPage {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        generation: u64,
        source_sql: String,
        dialect: crate::sql::SqlDialect,
        page: crate::model::pagination::PageRequest,
    },
    RunDerivedQuery {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        sql: String,
    },
    RunDerivedQueryPage {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        source_generation: u64,
        derived_generation: u64,
        source_sql: String,
        where_clause: String,
        order_by_clause: String,
        dialect: crate::sql::SqlDialect,
        page: crate::model::pagination::PageRequest,
    },
    ManualBegin {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualExecute {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        sql: String,
    },
    ManualExecutePage {
        connection: ConnectionIdentity,
        target: ExecutionTarget,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
        source_sql: String,
        dialect: crate::sql::SqlDialect,
        count_sql: String,
        page: crate::model::pagination::PageRequest,
    },
    ManualCommit {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    ManualRollback {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    RelationMutation {
        request: crate::db::mutation::RelationMutationRequest,
    },
    RelationCommit {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    RelationRollback {
        tab_id: Uuid,
        generation: u64,
        connection: ConnectionIdentity,
    },
    CancelQuery {
        tab_id: Uuid,
        generation: u64,
    },
    CancelManual {
        connection: ConnectionIdentity,
        tab_id: Uuid,
        query_generation: u64,
        transaction_generation: u64,
    },
    PersistWorkspace(crate::persistence::workspace::WorkspaceSnapshot),
    DeleteSqlFile(Uuid),
    WriteClipboard(ClipboardPayload),
    CheckSecretStoreAvailability,
    ScheduleCompletion(crate::sql::CompletionScheduleKey),
    Quit,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProfileOrganizationMutation {
    CreateGroup {
        id: Uuid,
        name: String,
    },
    RenameGroup {
        group_id: Uuid,
        name: String,
    },
    DeleteGroup {
        group_id: Uuid,
    },
    AssignProfile {
        profile_id: Uuid,
        group_id: Option<Uuid>,
    },
    MoveProfile {
        profile_id: Uuid,
        sibling_ids: Vec<Uuid>,
        direction: MoveDirection,
    },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProfileAccessChange {
    MakeGlobal,
    MakeProjectOnly(PathBuf),
    AddProject(PathBuf),
    RemoveProject(PathBuf),
}
